version: "3.7"
services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: linebot
    # environment:
    #   - PORT=22222
    volumes:
      - ~/volumes/linebot:/usr/src/app/logs
    restart: always
    ports: 
      - "${PORT}:${PORT}"
    env_file:
      - dev.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx

